---
title: "spotifyproject"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
spotifydata <- read_csv("spotifydata.csv")
genredata <- read_csv("data_by_genres.csv")
```


```{r}
#sort all data by increasing popularity, 100 = most popular
spotifydata <- spotifydata[order(-spotifydata$popularity),]
genredata <- genredata[order(-genredata$popularity),]
```

```{r}
library(ggplot2)

spotify2020 <- spotifydata[spotifydata$year == 2020,]

# acousticness, more acousticness = a little less popular
ggplot(spotify2020, aes(x = acousticness, y = popularity)) +
  geom_point(position = "jitter") +
  geom_smooth(method = "lm") +
  theme_bw() +
  ggtitle("Popularity of Music According to Acousticness in 2020")

# speechiness, more speechiness = a little more popular however more songs are less speechy
ggplot(spotify2020, aes(x = speechiness, y = popularity)) +
  geom_point(position = "jitter") +
  geom_smooth(method = "lm") +
  theme_bw() +
  ggtitle("Popularity of Music According to Speechiness in 2020")

```


```{r}
samplespotify <- spotifydata[sample(nrow(spotifydata), size = 1000, replace = FALSE),]
decades <- spotifydata[spotifydata$year > 1920,]
decadesample <- decades[sample(nrow(decades), size = 1000, replace = FALSE),]
#change x axis from 1950-now

#speechiness over time, higher production technologies has lead to less speechiness in music
ggplot(samplespotify, aes(x = year, y = speechiness)) +
  geom_line() +
  theme_bw() +
  ggtitle("Speechiness in Music Over Time") +
  geom_rect(aes(xmin=1950, xmax=1970, ymin=0, ymax=0.6), fill ="yellow", alpha=0.005)

#ggplot(decadesample, aes(x = year, y = valence)) +
  #geom_line() +
  #theme_bw() +
  #ggtitle("Loudness in Music Over Time")
```

```{r}
library(dplyr)
library(gridExtra)

par(mfrow=c(3,1))

#defining characteristics within each genre
popgenres <- genredata %>% filter(genres == "indie pop" | genres == "r&b" | genres == "rap" | genres == "edm" | genres == "alternative rock")

popgraph <- ggplot(popgenres, aes(x = genres, y = popularity, fill = genres)) +
  geom_col() +
  theme_bw()

#high energy = more intensity and activity.
energygraph <- ggplot(popgenres, aes(x = genres, y = energy, fill = genres)) +
  geom_col() +
  theme_bw() +
  ggtitle("Average Energy and Popularity According to Genre")

#high valence = cheerful, euphoric, positive: low valence = sad, depressed, negative
valencegraph <- ggplot(popgenres, aes(x = genres, y = valence, fill = genres)) +
  geom_col() +
  theme_bw() +
  ggtitle("Average Valence and Popularity According to Genre")

#high danceability = suitable track for dancing based on a combination of musical elements
dancegraph <- ggplot(popgenres, aes(x = genres, y = danceability, fill = genres)) +
  geom_col() +
  theme_bw() +
  ggtitle("Average Danceability and Popularity According to Genre")

#high tempo = faster
tempograph <- ggplot(popgenres, aes(x = genres, y = tempo, fill = genres)) +
  geom_col() +
  theme_bw() +
  ggtitle("Average Tempo and Popularity According to Genre")

grid.arrange(energygraph, tempograph)
grid.arrange(valencegraph, dancegraph)

```


